name: 'Hive consensus tests' 

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      parallelism:
        description: 'Number of concurrently running tests in each job. With 1 or 2 timeout is likely. With 4 or more false-positive fails are likely. Recommended is 3 to avoid timeouts and reduce false-positives'
        required: true
        default: '3'
        type: choice
        options: ['1', '2', '3', '4', '8', '16']

jobs:
  test_1:
    name: 1. Combined tests (e.g. stArgsZeroOneBalance)
    runs-on: ubuntu-latest
    steps:
      - name: Set up parameters
        run: |
          echo "PARALLELISM=${{ github.event.inputs.parallelism || '3' }}" >> $GITHUB_ENV
      - name: Check out Nethermind repository
        uses: actions/checkout@v3
        with:
          path: nethermind
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: nethermind
          file: nethermind/Dockerfile
          tags: nethermind:test-${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Check out Hive repository
        uses: actions/checkout@v3
        with:
          repository: ethereum/hive
          ref: master
          path: hive
      - name: Patch Hive Dockerfile
        run: sed -i 's#FROM nethermindeth/hive:$branch#FROM nethermind:test-${{ github.sha }}#g' hive/clients/nethermind/Dockerfile
      - name: Build Hive
        working-directory: hive
        run: go build .
      - name: Load Docker image
        run: docker load --input /tmp/image.tar
      
      - name: Run stArgsZeroOneBalance
        continue-on-error: true
        working-directory: hive
        run: ./hive --client nethermind --sim ethereum/consensus --sim.limit /(stArgsZeroOneBalance|stAttackTest) --sim.parallelism $PARALLELISM
      
      - name: Print results
        run: |
          chmod +x nethermind/scripts/hive-results.sh
          nethermind/scripts/hive-results.sh "hive/workspace/logs/*.json"
